kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mastodon-postgres
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi