apiVersion: v1
kind: Service
metadata:
  name: mastodon-postgres
  namespace: default
spec:
  type: NodePort
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: mastodon-postgres