apiVersion: v1
kind: Service
metadata:
  name: mastodon-redis
  namespace: default
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: mastodon-redis